In [2]:
import torch

In [17]:
# 1. 2D텐서를 만들고 차원0 위치에 크기가 1인 차원을 추가하시오.
x = torch.Tensor(3,3)
x = x.unsqueeze(0)
x

tensor([[[1.0286e-38, 1.0653e-38, 1.0194e-38],
         [8.4490e-39, 1.0469e-38, 9.3674e-39],
         [9.9184e-39, 8.7245e-39, 9.2755e-39]]])

In [18]:
# 2. 이전 텐서에 추가한 차원을 삭제하시오.
x = x.squeeze(0)
x

tensor([[1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])

In [23]:
# 3. 범위가 3-7 이고 크기가 5*3인 랜덤한 텐서를 만드시오.
y = torch.rand(5,3) * 4 + 3
y

tensor([[4.2236, 3.9938, 4.4574],
        [4.2613, 3.7386, 3.6164],
        [6.2999, 5.5144, 6.9882],
        [6.9604, 3.8956, 4.9278],
        [4.4845, 5.5733, 3.2977]])

In [22]:
# 4. 정규분포를 사용해 텐서를 만드시오.
z = torch.rand(3,3)
z.normal_() # _를 붙이면 해당 객체에 바로 적용된다.


tensor([[-0.1225,  0.4266,  0.4521],
        [-0.3572,  1.5282,  1.4613],
        [-0.7152, -2.3724,  0.3426]])

In [24]:
# 5. 텐서 torch.Tensor([1,1,1,0,1])에서 0이 아닌 원소의 인덱스를 추출하시오.
a = torch.Tensor([1,1,1,0,1])
torch.nonzero(a) # 2차원 텐서 반환 / 갯수는 count_nozero()함수 사용

tensor([[0],
        [1],
        [2],
        [4]])

In [25]:
# 6. 크기가 3*1인 랜덤한 텐서를 만들고 네 벌을 복사해 쌓으시오.
a = torch.rand(3,1)
a.expand(3,4) # expand는 크기가 1인 차원을 변경하므로 1인 아닌 차원은 (-1,1)이런식으로 -1로 나타내도 된다.

tensor([[0.8320, 0.8320, 0.8320, 0.8320],
        [0.4662, 0.4662, 0.4662, 0.4662],
        [0.6040, 0.6040, 0.6040, 0.6040]])

In [28]:
# 7. 2차원 행렬 두 개의 배치행렬곱셈을 계산하시오
a = torch.rand(3, 4, 5)
b = torch.rand(3, 5, 4)
print(a)
print(b)
torch.bmm(a,b) # (a,b,c) 에서 a를 배치차원으로 인식 따라서 a는 둘 모두 같아야 한다.

tensor([[[0.0118, 0.2286, 0.5674, 0.8523, 0.3331],
         [0.3322, 0.1903, 0.7520, 0.2666, 0.9728],
         [0.5364, 0.0012, 0.7651, 0.9060, 0.4654],
         [0.1012, 0.6038, 0.2742, 0.8664, 0.4653]],

        [[0.7991, 0.8477, 0.7348, 0.9661, 0.3108],
         [0.0519, 0.5879, 0.9544, 0.9663, 0.6331],
         [0.4647, 0.4000, 0.9771, 0.3971, 0.4856],
         [0.7615, 0.0521, 0.9655, 0.0435, 0.5710]],

        [[0.6356, 0.3044, 0.7724, 0.0032, 0.3823],
         [0.6858, 0.7843, 0.4413, 0.0392, 0.5940],
         [0.2402, 0.9044, 0.8435, 0.2996, 0.1557],
         [0.7496, 0.8964, 0.4538, 0.5640, 0.1544]]])
tensor([[[0.0202, 0.5333, 0.9042, 0.3082],
         [0.4403, 0.6752, 0.0812, 0.3761],
         [0.6415, 0.1084, 0.0170, 0.5182],
         [0.6949, 0.6584, 0.2791, 0.7985],
         [0.4632, 0.3489, 0.3648, 0.9716]],

        [[0.3717, 0.1196, 0.5659, 0.5470],
         [0.4790, 0.7807, 0.3097, 0.0557],
         [0.6478, 0.8524, 0.5162, 0.0929],
         [0.0249, 0.2778, 0.6589, 0.

tensor([[[1.2114, 0.8994, 0.3982, 1.3878],
         [1.2088, 0.9021, 0.7579, 1.7217],
         [1.3474, 1.1287, 0.9208, 1.7379],
         [1.2614, 1.2241, 0.5568, 1.5442]],

        [[1.3026, 1.6601, 1.8775, 1.3370],
         [1.1457, 1.5634, 1.6401, 0.9557],
         [1.1624, 1.3235, 1.3824, 0.7133],
         [1.1171, 0.9815, 1.2441, 0.5812]],

        [[0.9516, 1.0658, 1.1067, 0.7951],
         [1.4052, 1.4335, 1.1516, 1.1516],
         [1.5079, 0.8390, 1.3318, 1.3271],
         [1.5940, 1.3875, 1.4225, 1.6780]]])

In [29]:
# 8. 3차원 행렬과 2차원 행렬의 배치행렬곱셈을 계산하시오.
a = torch.rand(3,4,5)
b = torch.rand(5,4)
torch.matmul(a,b)
'''
좀 더 풀어써보면 
a 와 b의 배치 차원을 맞춰 주기 위해 b.squeeze(0)으로 (1,5,4)의 형태로 만들어주고 
다시 b.expand(3,-1,-1)을 해준다. 이를 요약하면 b.squeeze(0).expand(3,-1,-1)이 된다.
또는 파이썬의 *,**을 이용해서(파라미터로 몇개를 받을지 모르는 경우에 사용)
expand(a.size(0),*b.size())를 사용한다.
'''

tensor([[[1.3585, 1.0596, 1.0211, 1.4276],
         [0.7745, 0.6044, 1.1082, 0.9421],
         [1.0998, 0.8701, 1.1597, 1.2275],
         [1.9845, 1.4836, 1.2287, 2.0866]],

        [[2.0476, 1.4382, 1.4865, 2.1747],
         [1.1005, 0.6796, 0.2141, 1.1122],
         [1.5272, 1.1460, 1.5054, 1.6594],
         [1.4899, 0.9071, 0.7807, 1.4823]],

        [[2.0466, 1.4426, 1.2126, 2.1770],
         [0.7812, 0.5548, 0.5392, 0.7053],
         [1.9457, 1.5063, 1.2720, 2.0239],
         [1.7580, 1.4101, 0.7409, 1.7492]]])